CarDoctors/CarDoctors.MVC/Models/VehicleViewModel.cs
using System.Text.Json.Serialization;

namespace CarDoctors.MVC.Models
{
    public class VehicleViewModel
    {
        [JsonIgnore]
        public int ID { get; set; }

        public string VIN { get; set; }

        public string Model { get; set; }

        public string Manufacturer { get; set; }

        public string VehicleType { get; set; }

        public string Owner { get; set; }

        public string RegistrationPlate { get; set; }

        public string Picture { get; set; }
    }
}

CarDoctors/CarDoctors.MVC/Areas/Admin/Controllers/VehicleController.cs
using AutoMapper;
using CarDoctors.Data.CarDoctorsDbContext;
using CarDoctors.MVC.Models;
using CarDoctors.Services.Mappers;
using CarDoctors.Services.Models.InputModels;
using CarDoctors.Services.Models.PagingModels;
using CarDoctors.Services.Services.Contracts;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarDoctors.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class VehicleController : Controller
    {
        private readonly IVehicleServices vehicleServices;
        private readonly IMapper mapper;
        private readonly CarDoctorsContext carDoctorsContext;

        public VehicleController(CarDoctorsContext carDoctorsContext, IVehicleServices vehicleServices, IMapper mapper)
        {
            this.vehicleServices = vehicleServices;
            this.mapper = mapper;
            this.carDoctorsContext = carDoctorsContext;
        }

        public async Task<IActionResult> Index(PaginatedListGetModel<VehicleViewModel> model, int id, int pageNumber = 1, int PageSize = 6)
        {
            try
            {
                var optionsModel = new PagingOptionsModelVehicle()
                {
                    Page = pageNumber,
                    PageSize = PageSize,
                    SortBy = model.SortBy,
                    SortInDescendingOrder = model.SortInDescendingOrder
                };

                var booleans = new List<SelectListItem>()
                {
                    new SelectListItem()
                    {
                        Text = "True",
                        Value = "true"
                    },
                    new SelectListItem()
                    {
                        Text = "False",
                        Value = "False"
                    }
                };

                ViewData["Sort"] = booleans;

                var vehicles = await this.vehicleServices.GetPaginatedAsync(optionsModel, id);

                model = mapper.Map<PaginatedListGetModel<VehicleViewModel>>(vehicles);

                return View(model);
            }
            catch (Exception e)
            {

                ModelState.AddModelError(string.Empty, e.Message);

                var vehicles = await this.vehicleServices
                   .GetPaginatedAsync(new PagingOptionsModelVehicle(), id);

                model = mapper.Map<PaginatedListGetModel<VehicleViewModel>>(vehicles);

                return View(model);
            }
        }

        public async Task<IActionResult> Details(int id = 0)
        {
            if (id == 0)
            {
                return View();
            }

            var vehicle = await this.vehicleServices.Get(id);

            return View(vehicle);
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Admin")]
        public IActionResult Create()
        {
            var types = this.carDoctorsContext.VehicleTypes
              .Select(a => new VehicleTypeViewDataModel()
              {
                  VehicleTypeID = a.VehicleTypeID,
                  Type = a.Name
              });

            ViewData["VehicleTypeID"] = new SelectList(types, "VehicleTypeID", "Type");

            var owner = this.carDoctorsContext.Users
              .Select(a => new VehicleOwnerView()
              {
                  OwnerID = a.Id,
                  OwnerName = $"{a.FirstName} {a.LastName}"
              });

            ViewData["OwnerID"] = new SelectList(owner, "OwnerID", "OwnerName");

            return View();
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Admin")]
        public async Task<IActionResult> CreateAsync(VehicleViewInputModel input, int pageSize)
        {
            if (ModelState.IsValid)
            {
                var vehicleType = await this.carDoctorsContext.VehicleTypes.FirstOrDefaultAsync(v => v.VehicleTypeID == input.VehicleTypeID);

                var owner = await this.carDoctorsContext.Users.FirstOrDefaultAsync(v => v.Id == input.OwnerID);

                var vehicle = new VehicleInputModel()
                {
                    VIN = input.VIN,
                    Model = input.Model,
                    Type = vehicleType.Name,
                    Manufacturer = input.Manufacturer,
                    OwnerFirstName = owner.FirstName,
                    OwnerLastName = owner.LastName,
                    RegistrationPlate = input.RegistrationPlate
                };

                await this.vehicleServices.Create(vehicle);

                var vehicles = this.vehicleServices.GetAll(input.OwnerID);

                var json = Json(new { isValid = true, html = Helper.Helper.RenderRazorViewToString(this, "_ViewAll", vehicles) });

                return json;
            }
            else
            {
                var types = this.carDoctorsContext.VehicleTypes
              .Select(a => new VehicleTypeViewDataModel()
              {
                  VehicleTypeID = a.VehicleTypeID,
                  Type = a.Name
              });

                ViewData["VehicleTypeID"] = new SelectList(types, "VehicleTypeID", "Type");

                var owner = this.carDoctorsContext.Users
                  .Select(a => new VehicleOwnerView()
                  {
                      OwnerID = a.Id,
                      OwnerName = $"{a.FirstName} {a.LastName}"
                  });

                ViewData["OwnerID"] = new SelectList(owner, "OwnerID", "OwnerName");

                return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Create", input) });
            }
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Admin")]
        public async Task<IActionResult> UpdateAsync(int id)
        {
            var types = this.carDoctorsContext.VehicleTypes
              .Select(a => new VehicleTypeViewDataModel()
              {
                  VehicleTypeID = a.VehicleTypeID,
                  Type = a.Name
              });

            ViewData["VehicleTypeID"] = new SelectList(types, "Type", "Type");

            var vehicle = await this.vehicleServices.Get(id);

            var inputModel = new VehicleInputModel()
            {
                Manufacturer = vehicle.Manufacturer,
                Model = vehicle.Model,
                Type = vehicle.VehicleType,
                OwnerFirstName = vehicle.Owner.Split().First(),
                OwnerLastName = vehicle.Owner.Split().Last(),
                VIN = vehicle.VIN,
                RegistrationPlate = vehicle.RegistrationPlate,
                VehicleID = id
            };

            return View(inputModel);
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Admin")]
        public async Task<IActionResult> UpdateAsync(VehicleInputModel input, int id)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await this.vehicleServices.Update(input, id);

                    var vehicles = this.carDoctorsContext.Vehicles.MapVehicleDTO();

                    var json = Json(new { isValid = true, html = Helper.Helper.RenderRazorViewToString(this, "_ViewAll", vehicles) });

                    return json;
                }
                catch (Exception e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);

                    var types = this.carDoctorsContext.VehicleTypes
                      .Select(a => new VehicleTypeViewDataModel()
                      {
                          VehicleTypeID = a.VehicleTypeID,
                          Type = a.Name
                      });

                    ViewData["VehicleTypeID"] = new SelectList(types, "Type", "Type");

                    return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Update", input) });
                }
            }
            else
            {
                var types = this.carDoctorsContext.VehicleTypes
                      .Select(a => new VehicleTypeViewDataModel()
                      {
                          VehicleTypeID = a.VehicleTypeID,
                          Type = a.Name
                      });

                return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Update", input) });
            }
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            this.vehicleServices.Delete(id);

            var vehiclesToReturn = this.vehicleServices.GetAll(0);

            return Json(new { html = Helper.Helper.RenderRazorViewToString(this, "_ViewAll", vehiclesToReturn) });
        }
    }
}

CarDoctors/CarDoctors.MVC/Areas/Customer/Controllers/VehicleController.cs
using AutoMapper;
using CarDoctors.Data.CarDoctorsDbContext;
using CarDoctors.MVC.Models;
using CarDoctors.Services.Models.PagingModels;
using CarDoctors.Services.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CarDoctors.MVC.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class VehicleController : Controller
    {
        private readonly IVehicleServices vehicleServices;
        private readonly IMapper mapper;
        private readonly CarDoctorsContext carDoctorsContext;

        public VehicleController(CarDoctorsContext carDoctorsContext, IVehicleServices vehicleServices, IMapper mapper)
        {
            this.vehicleServices = vehicleServices;
            this.mapper = mapper;
            this.carDoctorsContext = carDoctorsContext;
        }

        public async Task<IActionResult> Index(PaginatedListGetModel<VehicleViewModel> model, string Email, int pageNumber = 1, int PageSize = 6)
        {
            try
            {
                if (model.SortBy == "Price")
                {
                    model.SortBy = "VIN";
                }

                var optionsModel = new PagingOptionsModelVehicle()
                {
                    Page = pageNumber,
                    PageSize = PageSize,
                    SortBy = model.SortBy,
                    SortInDescendingOrder = model.SortInDescendingOrder
                };

                var owner = await this.carDoctorsContext.Users.FirstOrDefaultAsync(x => x.Username == Email);

                var booleans = new List<SelectListItem>()
                {
                    new SelectListItem()
                    {
                        Text = "True",
                        Value = "true"
                    },
                    new SelectListItem()
                    {
                        Text = "False",
                        Value = "False"
                    }
                };

                ViewData["Sort"] = booleans;

                var vehicles = await this.vehicleServices
                    .GetPaginatedAsync(optionsModel, owner.Id);

                model = mapper.Map<PaginatedListGetModel<VehicleViewModel>>(vehicles);

                return View(model);
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);

                var owner = await this.carDoctorsContext.Users.FirstOrDefaultAsync(x => x.Username == Email);

                var vehicles = await this.vehicleServices
                   .GetPaginatedAsync(new PagingOptionsModelVehicle(), owner.Id);

                model = mapper.Map<PaginatedListGetModel<VehicleViewModel>>(vehicles);

                return View(model);
            }
        }

        public async Task<IActionResult> Details(int id = 0)
        {
            if (id == 0)
            {
                return View();
            }

            var visit = await this.vehicleServices.Get(id);

            return View(visit);
        }
    }
}

CarDoctors/CarDoctors.MVC/Areas/Admin/Views/Vehicle/Create.cshtml
@model VehicleViewInputModel

@{ Layout = null; }

<div>
    <form asp-area="Admin" asp-controller="Vehicle" asp-action="Create" onsubmit="return jQueryAjaxPost(this);">
        <div class="row">
            <div class="col-md-6">
                <div asp-validation-summary="All"></div>
                <div class="form-group">
                    <h5><label class="control-label">Type</label></h5>
                    <select asp-for="VehicleTypeID" class="form-control" asp-items="ViewBag.VehicleTypeID"></select>
                    <span asp-validation-for="VehicleTypeID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <h5><label class="control-label">Manufacturer</label></h5>
                    <input asp-for="@Model.Manufacturer" class="form-control" />
                    <span asp-validation-for="Manufacturer" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <h5><label class="control-label">Model</label></h5>
                    <input asp-for="@Model.Model" class="form-control" />
                    <span asp-validation-for="Model" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <h5><label class="control-label">VIN</label></h5>
                    <input asp-for="@Model.VIN" class="form-control" />
                    <span asp-validation-for="VIN" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <h5><label class="control-label">Owner</label></h5>
                    <select asp-for="OwnerID" class="form-control" asp-items="ViewBag.OwnerID"></select>
                    <span asp-validation-for="OwnerID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <h5><label class="control-label">Registration Plate</label></h5>
                    <input asp-for="@Model.RegistrationPlate" class="form-control" />
                    <span asp-validation-for="RegistrationPlate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="col-md-6 offset-md-3">
                        <center><input type="submit" value="Submit" class="btn" style="background-color: #3E5279; color: #f7f3e9;" /></center>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

CarDoctors/CarDoctors.MVC/Areas/Admin/Views/Vehicle/Details.cshtml
@model VehicleDTO

@{ Layout = null; }


<div class="card-body">
    <img src=@Model.Picture class="card-img-top" alt="...">
    <h5 class="card-title">Vehicle ID - @Model.ID</h5>
    <h5 class="card-title">Vehicle type - @Model.VehicleType</h5>
    <h5 class="card-title">VIN - @Model.VIN</h5>
    <h5 class="card-title">Manufacturer - @Model.Manufacturer</h5>
    <h5 class="card-title">Model - @Model.Model</h5>
    <h5 class="card-title">Owner - @Model.Owner</h5>
    <h5 class="card-title">Registration plate - @Model.RegistrationPlate</h5>
</div>

CarDoctors/CarDoctors.MVC/Areas/Admin/Views/Vehicle/Index.cshtml
@model PaginatedListGetModel<VehicleViewModel>

<center><h1 style="color: #3E5279;">List of All Vehicles</h1></center>

@{ ViewData["Title"] = "Index"; }

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model.Elements)
</div>

<br />

@{
    var prevDisabled = !Model.Previous ? "disabled" : "";
    var nextDisabled = !Model.Next ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-pageNumber="@(Model.CurrentPage - 1)"
   asp-route-pageSize="@(Model.PageSize)"
   asp-route-SortBy="@(Model.SortBy)"
   asp-route-OwnerID="@(Model.OwnerID)"
   asp-route-SortInDescendingOrder="@(Model.SortInDescendingOrder)"
    class="btn  @prevDisabled"style="background-color: #3E5279; color: #f7f3e9;">Previous</a>

<a asp-action="Index"
   asp-route-pageNumber="@(Model.CurrentPage + 1)"
   asp-route-pageSize="@(Model.PageSize)"
   asp-route-SortBy="@(Model.SortBy)"
   asp-route-OwnerID="@(Model.OwnerID)"
   asp-route-SortInDescendingOrder="@(Model.SortInDescendingOrder)"
   class="btn @nextDisabled" style="background-color: #3E5279; color: #f7f3e9;">Next</a>

<hr />


<div>
    <div asp-validation-summary="All" class="text text-danger"></div>
    <form asp-action="Index" style="color: #3E5279;
">
        <div class="row">
            <div class="col">
                <h3>Paging Options</h3>
            </div>
            <div class="col">
                <h3>Filter Options</h3>
            </div>
        </div>

        <hr />

        <div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <h5><label class="control-label">Page Index</label></h5>
                        <input asp-for="CurrentPage" class="form-control" />
                        <span asp-validation-for="CurrentPage" class="text text-danger"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <h5><label class="control-label">Owner ID</label></h5>
                        <input asp-for="OwnerID" class="form-control" />
                        <span asp-validation-for="OwnerID" class="text text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <h5>
                            <label class="control-label">Page Size</label>
                        </h5>
                        <input asp-for="PageSize" class="form-control" />
                        <span asp-validation-for="PageSize" class="text text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <h5>
                            <label class="control-label">Sort By</label>
                        </h5>
                        <input asp-for="SortBy" class="form-control" />
                        <span asp-validation-for="SortBy" class="text text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <h5>Sort in descending order</h5>
                    <div class="form-group">
                        <select asp-for="SortInDescendingOrder" asp-items="ViewBag.Sort" class="form-control"></select>
                    </div>
                </div>
            </div>

            <hr />

            <div class="form-group">
                <input type="submit" value="View" class="btn" style="background-color: #3E5279; color: #f7f3e9;" />
            </div>

        </div>
    </form>
</div>


@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarDoctors/CarDoctors.MVC/Areas/Admin/Views/Vehicle/Update.cshtml
@model VehicleInputModel


@{ Layout = null; }

<div class="col-md-4">
    <form asp-action="Update" asp-route-id="@Model.VehicleID" onsubmit="return jQueryAjaxPost(this);" >
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <h5><label class="control-label">Vehicle Type</label></h5>
            <select asp-for="@Model.Type" class="form-control" asp-items="ViewBag.VehicleTypeID"></select>
        </div>
        <div class="form-group">
            <h5><label class="control-label">Manufacturer</label></h5>
            <input asp-for="@Model.Manufacturer" class="form-control" />
            <span asp-validation-for="@Model.Manufacturer" class="text-danger"></span>
        </div>
        <div class="form-group">
            <h5><label class="control-label">Model</label></h5>
            <input asp-for="@Model.Model" class="form-control" />
            <span asp-validation-for="@Model.Model" class="text-danger"></span>
        </div>
        <div class="form-group">
            <h5><label class="control-label">VIN</label></h5>
            <input asp-for="@Model.VIN" class="form-control" />
            <span asp-validation-for="@Model.VIN" class="text-danger"></span>
        </div>
        <div class="form-group">
            <h5><label class="control-label">Registration Plate</label></h5>
            <input asp-for="@Model.RegistrationPlate" class="form-control" />
            <span asp-validation-for="@Model.RegistrationPlate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <h5><label class="control-label">Owner First Name</label></h5>
            <input asp-for="@Model.OwnerFirstName" class="form-control" />
            <span asp-validation-for="@Model.OwnerFirstName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <h5><label class="control-label">Owner Last Name</label></h5>
            <input asp-for="@Model.OwnerLastName" class="form-control" />
            <span asp-validation-for="@Model.OwnerLastName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Update" class="btn" style="background-color: #3E5279; color: #f7f3e9;" />
        </div>
    </form>
</div>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

CarDoctors/CarDoctors.MVC/Areas/Admin/Views/Vehicle/_ViewAll.cshtml
@model IEnumerable<VehicleViewModel>

<a onclick="showInPopup('@Url.Action("Create","Vehicle",new { Area = "Admin"},Context.Request.Scheme)','New Vehicle')" class="btn" style="background-color: #268426; color: #f7f3e9;"><i class="fas fa-plus"></i> New Vehicle</a>

<hr />

<div class="container">
    <div class="row">
        @foreach (var vehicle in Model)
        {
            <div class="col-sm-4">
                <div class="card" id="card" style="width: 18rem;">
                    <img src=@vehicle.Picture id="img-card" class="card-img-top" alt="...">
                    <div class="card-body" id="cardBody">

                        <h5 class="card-title">@vehicle.VIN</h5>
                        <h5 class="card-title">@vehicle.Manufacturer</h5>
                        <h5 class="card-title">@vehicle.Model</h5>
                        <h5 class="card-title">@vehicle.RegistrationPlate</h5>

                        <a onclick="showInPopup('@Url.Action("Details","Vehicle", new { Area = "Admin", id=vehicle.ID},Context.Request.Scheme)','Vehicle Details')" class="btn" style="background-color: #00778A; color: #f7f3e9;"><i class="fas fa-info"></i> Details</a>
                        <a onclick="showInPopup('@Url.Action("Update","Vehicle", new { Area = "Admin", id=vehicle.ID},Context.Request.Scheme)','Update Vehicle')" class="btn" style="background-color: #00778A; color: #f7f3e9;"><i class="fas fa-pencil-alt"></i> Update</a>
                        <br />
                        <br />
                        <form asp-action="Delete" asp-controller="Vehicle" asp-area="Admin" asp-route-id="@vehicle.ID" onsubmit="return jQueryAjaxDelete(this);">
                            <input type="submit" value="Delete" class="btn" style="background-color: #f05945; color: #f7f3e9;" />
                        </form>

                    </div>
                </div>
            </div>
        }
    </div>
</div>