CarDoctors/CarDoctors.MVC/Areas/Admin/Controllers/VisitController.cs
using AutoMapper;
using CarDoctors.Data.CarDoctorsDbContext;
using CarDoctors.MVC.Models;
using CarDoctors.Services.Mappers;
using CarDoctors.Services.Models.FilterModels;
using CarDoctors.Services.Models.InputModels;
using CarDoctors.Services.Models.PagingModels;
using CarDoctors.Services.Services.Contracts;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Dynamic.Core.Exceptions;
using System.Threading.Tasks;

namespace CarDoctors.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class VisitController : Controller
    {
        private readonly IVisitServices visitServices;
        private readonly CarDoctorsContext carDoctorsContext;
        private readonly IMapper mapper;

        public VisitController(IVisitServices visitServices, CarDoctorsContext carDoctorsContext, IMapper mapper)
        {
            this.visitServices = visitServices;
            this.carDoctorsContext = carDoctorsContext;
            this.mapper = mapper;
        }

        public async Task<IActionResult> IndexAsync(PaginatedListGetModel<VisitViewModel> inputModel, int pageNumber = 1, int PageSize = 6)
        {
            try
            {
                var vehicles = this.carDoctorsContext.Vehicles.Select(x => new VehicleViewDataModel()
                {
                    VehicleID = x.VehicleID,
                    Vehicle = $"{x.VehicleModel.Manufacturer.Name} {x.VehicleModel.Model} {x.RegistrationPlate}"
                });

                ViewData["VehicleID"] = new SelectList(vehicles, "VehicleID", "Vehicle");

                var booleans = new List<SelectListItem>()
                {
                    new SelectListItem()
                    {
                        Text = "True",
                        Value = "true"
                    },
                    new SelectListItem()
                    {
                        Text = "False",
                        Value = "False"
                    }
                };

                ViewData["Sort"] = booleans;

                var filter = new FilterVisits()
                {
                    VehicleID = inputModel.VehicleID,
                    DateFrom = inputModel.DateFrom,
                    DateTo = inputModel.DateTo
                };

                var optionsModel = new PagingOptionsModelVisit()
                {
                    Page = pageNumber,
                    PageSize = PageSize,
                    SortBy = inputModel.SortBy,
                    SortInDescendingOrder = inputModel.SortInDescendingOrder
                };

                var visits = await this.visitServices.GetPaginatedAsync(optionsModel, filter);

                inputModel = mapper.Map<PaginatedListGetModel<VisitViewModel>>(visits);

                return View(inputModel);
            }
            catch (ParseException)
            {
                ModelState.AddModelError(string.Empty, "Invalid Sort By criteria");

                return View(inputModel);
            }
            catch (Exception e)
            {

                ModelState.AddModelError(string.Empty, e.Message);

                return View(inputModel);
            }
        }

        public async Task<IActionResult> Details(int id = 0)
        {
            if (id == 0)
            {
                return View();
            }

            var visit = await this.visitServices.Get(id);

            return View(visit);
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Admin")]
        public IActionResult Create()
        {
            var vehicles = this.carDoctorsContext.Vehicles.Select(x => new VehicleViewDataModel()
            {
                VehicleID = x.VehicleID,
                Vehicle = $"{x.VehicleModel.Manufacturer.Name} {x.VehicleModel.Model} {x.RegistrationPlate}"
            });

            ViewData["VehicleID"] = new SelectList(vehicles, "VehicleID", "Vehicle");

            ViewData["VisitStatusID"] = new SelectList(this.carDoctorsContext.VisitStatuses, "StatusID", "Name");

            ViewData["ServiceID"] = new SelectList(this.carDoctorsContext.Services, "ServiceID", "ServiceName");

            return View();
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Admin")]
        public async Task<IActionResult> Create(VisitInputModel visitInputModel)
        {
            if (ModelState.IsValid)
            {
                visitInputModel.VisitDate = DateTime.Now;

                await this.visitServices.Create(visitInputModel);

                var optionsModel = new PagingOptionsModelVisit();

                var visits = await this.visitServices.GetPaginatedAsync(optionsModel, new FilterVisits());

                var json = Json(new { isValid = true, html = Helper.Helper.RenderRazorViewToString(this, "Index", visits) }); ;

                return json;
            }

            return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Create", visitInputModel) });
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Admin")]
        public async Task<IActionResult> Update(int id)
        {
            var vehicles = this.carDoctorsContext.Vehicles.Select(x => new VehicleViewDataModel()
            {
                VehicleID = x.VehicleID,
                Vehicle = $"{x.VehicleModel.Manufacturer.Name} {x.VehicleModel.Model} {x.RegistrationPlate}"
            });

            var visit = await this.visitServices.Get(id);

            var serviceIds = visit.ServicesDone.Split(", ").ToList();

            var visitStatus = await this.carDoctorsContext.VisitStatuses.FirstOrDefaultAsync(x => x.Name == visit.VisitStatus);

            var services = string.Join(" ", this.carDoctorsContext.Services.Where(s => serviceIds.Contains(s.ServiceName)).Select(x => x.ServiceID).ToList());

            var visitInput = new VisitInputModel()
            {
                VehicleID = visit.VehicleID,
                VisitDate = visit.VisitDate,
                PickupDate = visit.PickUpDate,
                VisitStatusID = visitStatus.StatusID,
                ServiceID = services
            };

            ViewData["VehicleID"] = new SelectList(vehicles, "VehicleID", "Vehicle");

            ViewData["VisitStatusID"] = new SelectList(this.carDoctorsContext.VisitStatuses, "StatusID", "Name");

            var servicesViewData = this.carDoctorsContext.Services
                .MapServiceDTO()
              .Select(a => new ServiceViewDataModel()
              {
                  ServiceID = a.ServiceID,
                  Service = a.ServiceName
              });

            ViewData["ServiceID"] = new SelectList(servicesViewData, "ServiceID", "Service");

            return View(visitInput);
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Admin")]
        public async Task<IActionResult> Update([Bind("VehicleID,PickupDate,VisitStatusID,ServiceID")] VisitInputModel visitInputModel, int id)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await this.visitServices.Update(visitInputModel, id);

                    var visits = this.visitServices.GetAll();

                    var json = Json(new { isValid = true, html = Helper.Helper.RenderRazorViewToString(this, "_ViewAll", visits) });

                    return json;
                }
                catch (Exception e)
                {
                    ModelState.AddModelError(null, e.Message);

                    return View();
                }
            }

            return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Create", visitInputModel) });
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            this.visitServices.Delete(id);

            var visitsToReturn = this.visitServices.GetAll();

            return Json(new { html = Helper.Helper.RenderRazorViewToString(this, "_ViewAll", visitsToReturn) });
        }
    }
}

CarDoctors/CarDoctors.MVC/Areas/Customer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Car Doctors</title>
    <link rel="preload" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" data-rocket-async="style" as="style" onload="this.onload=null;this.rel='stylesheet'" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" asp-append-version="true">
    <link rel="stylesheet" href="~/lib/bootstrap-multiselect/dist/css/bootstrap-multiselect.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" type="text/css" />
    <link rel="icon" href="~/assets/car_icon.ico">
    @using Microsoft.AspNetCore.Http;

</head>
<body style="background-color: #ffffff;">
    <header>
        <nav class="navbar navbar-expand-lg bg-whiteborder-bottom box-shadow mb-3 navbar-custom">
            <a class="navbar-brand" id="brand" asp-area="Customer" asp-controller="Home" asp-action="Index">CarDoctors</a>
            <button class="navbar-toggler" type="button" data-trigger="#main_nav">
                <span class="navbar-toggler-icon">
                    <i class="fas fa-bars" style="color:gray; font-size:28px;"></i>
                </span>
            </button>
            <div class="navbar-collapse" id="main_nav">
                <div class="offcanvas-header mt-3">
                    <button class="btn btn-outline-danger btn-close float-right"> &times Close </button>
                    <h5 class="py-2 text-black-50">Main navbar</h5>
                </div>

                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index"><i class="fa fa-fw fa-home"></i>Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Customer" asp-controller="Service" asp-action="Index" asp-route-Email=@Context.Session.GetString("Username")><i class="fa fa-fw fa-wrench"></i>Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Customer" asp-controller="Vehicle" asp-action="Index" asp-route-Email=@Context.Session.GetString("Username")><i class="fas fa-car-side"></i> Vehicles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Customer" asp-controller="Visit" asp-action="Index" asp-route-Email=@Context.Session.GetString("Username")><i class="fas fa-cart-arrow-down"></i> Visits</a>
                    </li>
                    <li class="nav-item">
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link" asp-area="Admin" asp-controller="Customer" asp-action="Index"><i class="fas fa-users"></i> Users</a>
                        }
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="AboutUs"><i class="fas fa-info"></i> About Us</a>
                    </li>
                </ul>
                <ul class="navbar-nav" id="partial-nav">
                    <partial name="_LoginPartial" />
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="modal fade" tabindex="-1" role="dialog" id="form-modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="modal-content">
                <div class="modal-header" id="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: #0a1931;">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>

    <div class="loaderbody" id="loaderbody">
        <div class="loader"></div>
    </div>

    <footer class="border-top footer " id="footer">
        <div class="container" style="color: #ffc947;">
            &copy; 2021 - Car Doctors - <a asp-area="Admin" asp-controller="Home" asp-action="AboutUs" style="color: #ffc947;">About Us</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-multiselect/dist/js/bootstrap-multiselect.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>