CarDoctors/CarDoctors.MVC/Models/ServiceViewModel.cs
namespace CarDoctors.MVC.Models
{
    public class ServiceViewModel
    {
        public int ServiceID { get; set; }
        public string ServiceName { get; set; }
        public double Price { get; set; }
        public string Currency { get; set; }
    }
}

CarDoctors/CarDoctors.MVC/Areas/Admin/Controllers/ServiceController.cs
using AutoMapper;
using CarDoctors.Data.CarDoctorsDbContext;
using CarDoctors.MVC.Models;
using CarDoctors.Services.Exceptions;
using CarDoctors.Services.Models.FilterModels;
using CarDoctors.Services.Models.InputModels;
using CarDoctors.Services.Models.PagingModels;
using CarDoctors.Services.Services.Contracts;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarDoctors.MVC.Helper;

namespace CarDoctors.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceController : Controller
    {
        private readonly IServiceServices serviceServices;
        private readonly IMapper mapper;
        private readonly CarDoctorsContext carDoctorsContest;

        public ServiceController(CarDoctorsContext carDoctorsContest, IServiceServices serviceServices, IMapper mapper)
        {
            this.serviceServices = serviceServices;
            this.mapper = mapper;
            this.carDoctorsContest = carDoctorsContest;
        }

        [AllowAnonymous]
        public async Task<IActionResult> IndexAsync(PaginatedListGetModel<ServiceViewModel> inputModel, int pageNumber = 1, int PageSize = 6)
        {
            try
            {
                var filter = new FilterServices()
                {
                    Name = inputModel.Name,
                    PriceIs = inputModel.PriceIs,
                    PriceFrom = inputModel.PriceFrom,
                    PriceTo = inputModel.PriceTo,
                    Currency = inputModel.Currency
                };

                var optionsModel = new PagingOptionsModelService()
                {
                    Page = pageNumber,
                    PageSize = PageSize,
                    SortBy = inputModel.SortBy,
                    SortInDescendingOrder = inputModel.SortInDescendingOrder
                };

                var booleans = new List<SelectListItem>()
                {
                    new SelectListItem()
                    {
                        Text = "True",
                        Value = "true"
                    },
                    new SelectListItem()
                    {
                        Text = "False",
                        Value = "False"
                    }
                };

                ViewData["Sort"] = booleans;

                var services = await this.serviceServices.GetPaginatedAsync(filter, optionsModel);

                inputModel = mapper.Map<PaginatedListGetModel<ServiceViewModel>>(services);

                return View(inputModel);
            }
            catch (InvalidCurrencyException e)
            {
                ModelState.AddModelError(string.Empty, e.Message);

                var services = await this.serviceServices.GetPaginatedAsync(new FilterServices(), new PagingOptionsModelService());

                inputModel = mapper.Map<PaginatedListGetModel<ServiceViewModel>>(services);

                return View(inputModel);
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);

                var services = await this.serviceServices.GetPaginatedAsync(new FilterServices(), new PagingOptionsModelService());

                inputModel = mapper.Map<PaginatedListGetModel<ServiceViewModel>>(services);

                return View(inputModel);
            }
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Admin")]
        public async Task<IActionResult> CreateAsync(ServiceInputModel service)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await this.serviceServices.Create(service);

                    var services = await this.serviceServices.GetAll(new FilterServices(), "BGN");

                    var json = Json(new { isValid = true, html = Helper.Helper.RenderRazorViewToString(this, "_ViewAll", services) });

                    return json;
                }
                catch (ObjectDuplicateException e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);

                    return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Create", service) });
                }
                catch (ObjectNullException e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);

                    return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Create", service) });
                }
                catch (NegativePriceException e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);

                    return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Create", service) });
                }
                catch (Exception e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);

                    return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Create", service) });
                }
            }

            return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Create", service) });
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Admin")]
        public async Task<IActionResult> UpdateAsync(int id)
        {
            var service = await this.carDoctorsContest.Services.Where(s => s.ServiceID == id).FirstOrDefaultAsync();

            var inputModel = new ServiceInputModel()
            {
                ServiceID = service.ServiceID,
                Name = service.ServiceName,
                Price = service.Price,
                Currency = service.Currency
            };

            return View(inputModel);
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Admin")]
        public async Task<IActionResult> UpdateAsync(ServiceInputModel input, int id)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var service = await this.carDoctorsContest.Services.Where(s => s.ServiceID == id).FirstOrDefaultAsync();

                    await this.serviceServices.Update(input, service.ServiceID);

                    var services = await this.serviceServices.GetAll(new FilterServices(), "BGN");

                    var json = Json(new { isValid = true, html = Helper.Helper.RenderRazorViewToString(this, "_ViewAll", services) });

                    return json;
                }
                catch (ObjectNotFoundException e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);

                    return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Update", input) });
                }
                catch (ObjectNullException e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);

                    return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Update", input) });
                }
                catch (NegativePriceException e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);

                    return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Update", input) });
                }
                catch (Exception e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);

                    return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Update", input) });
                }
            }

            return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Update", input) });
        }


        [HttpPost]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Admin")]
        public async Task<IActionResult> Delete(string name)
        {
            try
            {
                var service = await this.carDoctorsContest.Services.FirstOrDefaultAsync(s => s.ServiceName == name);

                this.serviceServices.Delete(service.ServiceID);

                var serviesToReturn = await this.serviceServices.GetAll(new FilterServices(), "BGN");

                return Json(new { html = Helper.Helper.RenderRazorViewToString(this, "_ViewAll", serviesToReturn) });
            }
            catch (ObjectNotFoundException e)
            {
                ModelState.AddModelError(string.Empty, e.Message);

                return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Delete", name) });
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);

                return Json(new { isValid = false, html = Helper.Helper.RenderRazorViewToString(this, "Delete", name) });
            }
        }
    }
}

CarDoctors/CarDoctors.MVC/Areas/Customer/Controllers/ServiceController.cs
using AutoMapper;
using CarDoctors.Data.CarDoctorsDbContext;
using CarDoctors.MVC.Models;
using CarDoctors.Services.Exceptions;
using CarDoctors.Services.Models.FilterModels;
using CarDoctors.Services.Models.PagingModels;
using CarDoctors.Services.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CarDoctors.MVC.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class ServiceController : Controller
    {
        private readonly IServiceServices serviceServices;
        private readonly IMapper mapper;
        private readonly CarDoctorsContext carDoctorsContest;

        public ServiceController(CarDoctorsContext carDoctorsContest, IServiceServices serviceServices, IMapper mapper)
        {
            this.serviceServices = serviceServices;
            this.mapper = mapper;
            this.carDoctorsContest = carDoctorsContest;
        }

        [AllowAnonymous]
        public async Task<IActionResult> IndexAsync(PaginatedListGetModel<ServiceViewModel> inputModel, int pageNumber = 1, int PageSize = 6)
        {
            try
            {
                var filter = new FilterServices()
                {
                    Name = inputModel.Name,
                    PriceIs = inputModel.PriceIs,
                    PriceFrom = inputModel.PriceFrom,
                    PriceTo = inputModel.PriceTo,
                    Currency = inputModel.Currency
                };

                var optionsModel = new PagingOptionsModelService()
                {
                    Page = pageNumber,
                    PageSize = PageSize,
                    SortBy = inputModel.SortBy,
                    SortInDescendingOrder = inputModel.SortInDescendingOrder
                };

                var booleans = new List<SelectListItem>()
                {
                    new SelectListItem()
                    {
                        Text = "True",
                        Value = "true"
                    },
                    new SelectListItem()
                    {
                        Text = "False",
                        Value = "False"
                    }
                };

                ViewData["Sort"] = booleans;

                var service = await this.serviceServices.GetPaginatedAsync(filter, optionsModel);

                inputModel = mapper.Map<PaginatedListGetModel<ServiceViewModel>>(service);

                return View(inputModel);
            }
            catch (InvalidCurrencyException e)
            {
                ModelState.AddModelError(string.Empty, e.Message);

                var services = await this.serviceServices.GetPaginatedAsync(new FilterServices(), new PagingOptionsModelService());

                var service = mapper.Map<PaginatedListGetModel<ServiceViewModel>>(services);

                return View(service);
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);

                var services = await this.serviceServices.GetPaginatedAsync(new FilterServices(), new PagingOptionsModelService());

                var service = mapper.Map<PaginatedListGetModel<ServiceViewModel>>(services);

                return View(service);
            }
        }

        [AllowAnonymous]
        public async Task<IActionResult> ClearFilter()
        {
            return RedirectToAction("Index");
        }
    }
}

CarDoctors/CarDoctors.MVC/Areas/Admin/Views/Service/Create.cshtml
@model ServiceInputModel

@{ Layout = null; }

<div >
    <form asp-action="Create" onsubmit="return jQueryAjaxPost(this);" >
        <div class="row">
            <div class="col-md-6">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <h5><label class="control-label">Service Name</label></h5>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <h5><label class="control-label">Service Price</label></h5>
                    <input asp-for="@Model.Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="col-md-6 offset-md-3">
                        <input type="submit" value="Submit" class="btn" style="background-color: #3E5279; color: #f7f3e9;" />
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

CarDoctors/CarDoctors.MVC/Areas/Admin/Views/Service/Index.cshtml
@model PaginatedListGetModel<ServiceViewModel>

<center><h1 id="header">List of Services</h1></center>

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model.Elements)
</div>

<br>

@{
    var prevDisabled = !Model.Previous ? "disabled" : "";
    var nextDisabled = !Model.Next ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-pageNumber="@(Model.CurrentPage - 1)"
   asp-route-pageSize="@(Model.PageSize)"
   asp-route-VehicleType="@(Model.VehicleType)"
   asp-route-VisitTo="@(Model.VisitTo)"
   asp-route-VisitFrom="@(Model.VisitFrom)"
   asp-route-VehicleModel="@(Model.VehicleModel)"
   asp-route-VehicleManufacturer="@(Model.VehicleManufacturer)"
   asp-route-Phone="@(Model.Phone)"
   asp-route-Email="@(Model.Email)"
   asp-route-SortBy="@(Model.SortBy)"
   asp-route-SortInDescendingOrder="@(Model.SortInDescendingOrder)"
   class="btn  @prevDisabled" id="buttonsPage">Previous</a>

<a asp-action="Index"
   asp-route-pageNumber="@(Model.CurrentPage + 1)"
     asp-route-pageSize="@(Model.PageSize)"
   asp-route-VehicleType="@(Model.VehicleType)"
   asp-route-VisitTo="@(Model.VisitTo)"
   asp-route-VisitFrom="@(Model.VisitFrom)"
   asp-route-VehicleModel="@(Model.VehicleModel)"
   asp-route-VehicleManufacturer="@(Model.VehicleManufacturer)"
   asp-route-Phone="@(Model.Phone)"
   asp-route-Email="@(Model.Email)"
   asp-route-SortBy="@(Model.SortBy)"
   asp-route-SortInDescendingOrder="@(Model.SortInDescendingOrder)"
   class="btn @nextDisabled" id="buttonsPage">Next</a>  

<hr />

<div>
    <div asp-validation-summary="All" class="text text-danger"></div>
    <form asp-action="Index" id="paging">
        <div class="row">
            <div class="col">
                <h3>Paging Options</h3>
            </div>
            <div class="col">
                <h3>Filter Options</h3>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <h5><label class="control-label">Page Index</label></h5>
                    <input asp-for="CurrentPage" class="form-control" />
                    <span asp-validation-for="CurrentPage" class="text text-danger"></span>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <h5><label class="control-label">Service Name</label></h5>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <h5>
                        <label class="control-label">Page Size</label>
                    </h5>
                    <input asp-for="PageSize" class="form-control" />
                    <span asp-validation-for="PageSize" class="text text-danger"></span>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <h5>
                        <label class="control-label">Service Price Is:</label>
                    </h5>
                    <input asp-for="PriceIs" class="form-control" />
                    <span asp-validation-for="PriceIs" class="text text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <h5>
                        <label class="control-label">Sort By</label>
                    </h5>
                    <input asp-for="SortBy" class="form-control" />
                    <span asp-validation-for="SortBy" class="text text-danger"></span>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <h5>
                        <label class="control-label">Service Price From:</label>
                    </h5>
                    <input asp-for="PriceFrom" class="form-control" />
                    <span asp-validation-for="PriceFrom" class="text text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <h5>Sort in descending order</h5>
                <div class="form-group">
                    <select asp-for="SortInDescendingOrder" asp-items="ViewBag.Sort" class="form-control"></select>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <h5>
                        <label class="control-label">Price To:</label>
                    </h5>
                    <input asp-for="PriceTo" class="form-control" />
                    <span asp-validation-for="PriceTo" class="text text-danger"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col">

            </div>

            <div class="col">
                <div class="form-group">
                    <h5>
                        <label class="control-label">Currency</label>
                    </h5>
                    <input asp-for="Currency" class="form-control" />
                    <span asp-validation-for="Currency" class="text text-danger"></span>
                </div>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <input type="submit" value="View" class="btn" id="buttonsPage" />
                </div>
            </div>
        </div>
    </form>

</div>


@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarDoctors/CarDoctors.MVC/Areas/Admin/Views/Service/Update.cshtml
@model ServiceInputModel

@{ Layout = null; }

<div class="row">
    <div class="col-md-12">
        <div asp-validation-summary="All" class="text-danger"></div>
        <form asp-action="Update" onsubmit="return jQueryAjaxPost(this);">
            <div class="row">
                <div class="col">
                    <a asp-route-name="@Model.Name"></a>
                    <div class="form-group">
                        <h5><label class="control-label">Service Name</label></h5>
                        <input asp-for="@Model.Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <h5><label class="control-label">Service Price</label></h5>
                        <input asp-for="@Model.Price" class="form-control" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <h5><label class="control-label">Currency</label></h5>
                        <input asp-for="@Model.Currency" class="form-control" />
                        <span asp-validation-for="Currency" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6 offset-md-3">
                            <input type="submit" value="Submit" class="btn" style="background-color: #3E5279; color: #f7f3e9;"/>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
    
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

CarDoctors/CarDoctors.MVC/Areas/Admin/Views/Service/_ViewAll.cshtml
@model IEnumerable<ServiceViewModel>

<a onclick="showInPopup('@Url.Action("Create","Service",new { Area = "Admin"},Context.Request.Scheme)','New Service')" class="btn" style="background-color: #268426; color: #f7f3e9;"><i class="fas fa-plus"></i> New Service</a>

<hr />  

<div class="container">
    <div class="row">
        @foreach (var service in Model)
        {
            <div class="col-sm-4">
                <div class="card" id="card" style="width: 18rem;">
                    <img src="/assets/fix.png" id="img-card" class="card-img-top" alt="...">
                    <div class="card-body" id="cardBody">
                        <h5 class="card-title">@service.ServiceName</h5>
                        <h5 class="card-title">@service.Price</h5>
                        <h5 class="card-title">@service.Currency</h5>


                        <a onclick="showInPopup('@Url.Action("Update","Service", new { Area = "Admin", id=service.ServiceID},Context.Request.Scheme)','Update Service')" class="btn" style="background-color: #00778A; color: #f7f3e9;"><i class="fas fa-info"></i> Update</a>

                        <br />
                        <br />

                        <form asp-action="Delete" asp-route-name="@service.ServiceName" onsubmit="return jQueryAjaxDelete(this);">
                            <input type="submit" value="Delete" class="btn" style="background-color: #f05945; color: #f7f3e9;" />
                        </form>

                    </div>
                </div>
            </div>
        }
    </div>
</div>